[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM9
monitor_port = COM9
lib_deps = 
    arduino-libraries/Servo@^1.2.1
    adafruit/Adafruit PWM Servo Driver Library@^2.4.0
